### ISSUE TITLE
extension issue

### ISSUE THREAD

**Issue by UHFT** [nvpro-samples/vk_mini_path_tracer#8] opened 2021-01-04 15:12 UTC
I'm running Vulkan SDK 1.2.162 on GTX 2080Ti (with driver 460.89). It compiles okay but I've got this error message when I run in debug mode.

_______________
Vulkan Version:
 - available:  1.2.162
 - requesting: 1.1.0
___________________________
Available Instance Layers :
VK_LAYER_NV_optimus (v. 1.2.155 1) : NVIDIA Optimus layer
VK_LAYER_VALVE_steam_overlay (v. 1.2.136 1) : Steam Overlay Layer
VK_LAYER_VALVE_steam_fossilize (v. 1.2.136 1) : Steam Pipeline Caching Layer
VK_LAYER_NV_nsight-sys (v. 1.1.97 2) : NVIDIA Nsight Systems profiler layer

Available Instance Extensions :
VK_KHR_device_group_creation (v. 1)
VK_KHR_display (v. 23)
VK_KHR_external_fence_capabilities (v. 1)
VK_KHR_external_memory_capabilities (v. 1)
VK_KHR_external_semaphore_capabilities (v. 1)
VK_KHR_get_display_properties2 (v. 1)
VK_KHR_get_physical_device_properties2 (v. 2)
VK_KHR_get_surface_capabilities2 (v. 1)
VK_KHR_surface (v. 25)
VK_KHR_surface_protected_capabilities (v. 1)
VK_KHR_win32_surface (v. 6)
VK_EXT_debug_report (v. 9)
VK_EXT_debug_utils (v. 2)
VK_EXT_swapchain_colorspace (v. 4)
VK_NV_external_memory_capabilities (v. 1)
______________________
Used Instance Layers :
VK_LAYER_KHRONOS_validation

Used Instance Extensions :
VK_EXT_debug_utils
C:\GitHub\VKRT\NVPro\shared_sources\nvvk\context_vk.cpp(305): Vulkan Error : VK_ERROR_LAYER_NOT_PRESENT
Assertion failed: !"Critical Vulkan Error", file C:\GitHub\VKRT\NVPro\shared_sources\nvvk\error_vk.cpp, line 119

C:\GitHub\VKRT\NVPro\bin_x64\Debug\vk_mini_path_tracer_1_hello_vulkan.exe (process 20628) exited with code 3.
Press any key to close this window . . .

Can you let me know how to resolve this?

**Comment by NBickford-NV** [comment] 2021-01-04 19:31
Hi UHFT! It looks like here the issue is that the validation layer isn't one of the available instance layers, for some reason - it should be installed with the Vulkan SDK, but at least one other person has run into this issue, so this seems to be a thing that can happen.

In the Windows Registry Editor, if you go to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ExplicitLayers`, do the keys include a path to a VkLayer_khronos_validation.json file? For reference, here's what the registry keys look like on my computer - VkLayer_khronos_validation.json is the 5th path listed:

![image](https://user-images.githubusercontent.com/57467222/103571649-19c42f00-4e80-11eb-93fe-5b7650bfa930.png)

(This is based on https://www.asawicki.info/news_1683_vulkan_layers_dont_work_look_at_registry)

**Comment by UHFT** [comment] 2021-01-04 20:51
![Screenshot 2021-01-04 at 19 52 09](https://user-images.githubusercontent.com/61891448/103578381-5d458a00-4ece-11eb-9e29-c1b79486a546.jpg)


The previous version HKEY was not removed in the list which corrupted registry. It works after manually removing the old version. Thanks.

**Comment by NBickford-NV** [comment] 2021-01-04 21:15
Ah, awesome! Closing this issue if that's OK.

**Closed as completed by NBickford-NV** 2021-01-04 21:15 UTC
